# Numpy
###### Numpy is a standard python library. 
###### Numpy is open-source library.
###### Numpy is used for Mathematical operations, Scientific computing, data analysis, etc..
###### Numpy will support n-dimensional array. 
###### Arrays are faster than the list.

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
l=range(1000)
%timeit [i**2 for i in l]

138 μs ± 1.31 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [5]:
a=np.arange(1000)
%timeit a**2

2.42 μs ± 185 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# creating array

In [6]:
a=np.array([1,2,3,4])

In [7]:
print(a.ndim)

1


In [8]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
print(b.ndim)

2


In [10]:
c=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [11]:
print(c.ndim)

3


In [12]:
c1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
print(c1.ndim)

3


In [14]:
print(a.shape)

(4,)


In [15]:
print(b.shape)

(2, 3)


In [16]:
print(c.shape)

(1, 4, 2)


In [17]:
print(c1.shape)

(2, 2, 2)


# Functions for sreating array

In [18]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


##### using line space

In [20]:
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [21]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
b=np.linspace(0,1,5)
print(b)

[0.   0.25 0.5  0.75 1.  ]


In [23]:
a=np.zeros((3,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [24]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
a=np.eye(3,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [26]:
a=np.eye(3,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [27]:
print(np.diag(a))

[1. 1. 1.]


# Basic data types

In [28]:
a=np.array(10)
print(a.dtype)

int64


In [29]:
a=np.arange(10,dtype="float64")
print(a.dtype)

float64


In [30]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# Other data type

In [31]:
a=np.array(1+2j+3j)
print(a.dtype)

complex128


In [32]:
a=np.array([True,False])
print(a.dtype)

bool


In [33]:
a=np.array(['Aparna','ramya'])
print(a.dtype)

<U6


 # Indexing and sclicing

In [34]:
a=np.arange(10)
print(a[5])

5


In [35]:
c=[5,6,7,8,10,20]
print(a[2])

2


In [36]:
a=np.diag([1,2,3])
print(a[2,1])

0


In [37]:
a[2,2]=6
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 6]]


# Slicing

In [38]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
print(a[1:8:2])# a[start:stop:step]

[1 3 5 7]


In [40]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

# Copies and Viewing

In [41]:
v=np.arange(10)
w=v[::2]
print(v)
print(w)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [42]:
print(np.shares_memory(v,w))

True


In [43]:
w[0]=20
print(v)
print(w)

[20  1  2  3  4  5  6  7  8  9]
[20  2  4  6  8]


In [44]:
e=np.arange(10)
f=e[::2].copy()
print(e)
print(f)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [47]:
print(np.shares_memory(e,f))

False


In [48]:
f[3]=25
print(e)
print(f)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4 25  8]


# Random Number Generator

In [52]:
a=np.random.randint(0,50,20)
print(a)

[46 36 18 30 44 28 30 46 30 36  5 35  5 41 18 25 25 40  4 26]


In [53]:
mask=(a%2==0)

In [54]:
mask_a=a[mask]
print(mask_a)

[46 36 18 30 44 28 30 46 30 36 18 40  4 26]


In [55]:
a[mask]=-1
print(a)

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1  5 35  5 41 -1 25 25 -1 -1 -1]


# Element wise Operations

### 1.Basic Operations

In [58]:
a=np.array([1,2,3,4])
print(a+2) # add 1's to whole array

[3 4 5 6]


In [59]:
print(a**3) #cubes the every element in that

[ 1  8 27 64]


### All Arithemtic operates Element wise

In [61]:
r=np.ones(4)+1
print("a= ",a)
print("r= ",r)

a=  [1 2 3 4]
r=  [2. 2. 2. 2.]


In [63]:
print(a*r) # both gets multiply 

[2. 4. 6. 8.]


In [64]:
a-r

array([-1.,  0.,  1.,  2.])

In [65]:
u=np.diag([1,2,3,4])
print(u)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [69]:
print(u*u)
print(" ")
print(u.dot(u))#dot product

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
 
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


## comparision operaters

In [71]:
print(a==r) #a=[1,2,3,4] while r=[2,2,2,2] from above

[False  True False False]


In [72]:
print(a<r) #checks every element and gives true or false

[ True False False False]


In [77]:
print(a>=r) # gives true only when it satisfy the condition

[False  True  True  True]


In [81]:
print(np.array_equal(a,r))

False


# Logical operators

In [91]:
q=np.array([1,0,0,1],dtype="bool")
p=np.array([0,1,1,1],dtype="bool")
print(np.logical_or(q,p)) # logical or operation

[ True  True  True  True]


In [92]:
print(np.logical_and(p,q))#logical and operation

[False False False  True]


In [93]:
print(np.logical_not(p)) #logical not operation

[ True False False False]


# Trigonometry funtions

In [94]:
g=np.arange(6)
print(g)

[0 1 2 3 4 5]


In [100]:
print(np.sin(g[3]))

0.1411200080598672


In [101]:
print(np.cos(g))

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [102]:
print(np.log(g[4]))

1.3862943611198906


In [104]:
print(np.exp(g))

[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]


# Basic reductions

In [105]:
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [106]:
x=np.array([[1,3],[4,6]])
print(x)

[[1 3]
 [4 6]]


In [110]:
x.sum(axis=1)

array([ 4, 10])

### Other reductions

In [111]:
print(x.min())

1


In [112]:
x.max()

np.int64(6)

In [114]:
print(x.argmin())

0


In [115]:
print(x.argmax())

3


### Statistics

In [117]:
print(x.mean())

3.5


In [120]:
h=np.array([2,5,7,8,1,5,4,6,2,1,2,9])
print(np.median(h))

4.5


In [123]:
print(h.std())

2.656229575084871
